[metadata]
configVersion = "0.0.38"

[environments.production.ios]
chatPollIntervalSeconds = 1
releaseFlags = {
  chat = true
  chatOptInV2 = true
  chatTestActive = true
  localServices = true
  notifications = true
  onboarding = true
  recentActivity = true
  search = true
  topics = true
}
chatBanner = {
  id = "govuk_chat_banner_10_2025"
  title = "Try GOV.UK Chat now"
  body = "Early access to GOV.UK Chat ends at 10am on 4 November."
  link = {
   title = "Ask a question"
   url = "govuk://gov.uk/chat"
  }
}

[environments.production.android]
releaseFlags = {
  chat = false
  chatOptIn = false
  chatTestActive = false
  localServices = true
  notifications = true
  onboarding = true
  recentActivity = true
  search = true
  topics = true
}

[environments.integration.ios]
chatPollIntervalSeconds = 1
refreshTokenExpirySeconds = 3540
releaseFlags = {
  chat = true
  chatOptInV2 = true
  chatTestActive = true
  localServices = true
  notifications = true
  onboarding = true
  recentActivity = true
  search = true
  topics = true
}
chatBanner = {
  id = "govuk_chat_banner_10_2025"
  title = "Try GOV.UK Chat now"
  body = "Early access to GOV.UK Chat ends at 10am on 4 November."
  link = {
   title = "Ask a question"
   url = "govuk://gov.uk/chat"
  }
}

[environments.integration.android]
refreshTokenExpirySeconds = 3540
releaseFlags = {
  chat = false
  chatOptIn = false
  chatTestActive = false
  localServices = true
  notifications = true
  onboarding = true
  recentActivity = true
  search = true
  topics = true
}

[environments.default.android]
platform = "Android"
available = true
minimumVersion = "0.0.1"
recommendedVersion = "0.0.1"
searchApiUrl = "https://search.publishing.service.gov.uk/v0_1/search.json"
refreshTokenExpirySeconds = 31532400
chatPollIntervalSeconds = 3
chatUrls = {
    termsAndConditions = "https://www.gov.uk/guidance/govuk-chat-terms-and-conditions"
    privacyNotice = "https://www.gov.uk/government/publications/govuk-chat-privacy-notice"
    about = "https://www.gov.uk/guidance/about-govuk-chat"
    feedback = "https://surveys.publishing.service.gov.uk/s/SUIEH2/"
}
userFeedbackBanner = {
  body = "Tell us what you think about the app"
  link = {
   title = "Give feedback"
   url = "https://www.gov.uk/contact/govuk-app"
  }
}
alertBanner = {
  id = "govuk_improve_app_alert_10_2025"
  body = "Help improve the app"
  link = {
   title = "Take a 5 minute survey"
   url = "https://surveys.publishing.service.gov.uk/s/GOVUK-APP"
  }
}

[environments.default.ios]
platform = "iOS"
available = true
minimumVersion = "0.0.1"
recommendedVersion = "0.0.1"
searchApiUrl = "https://search.publishing.service.gov.uk/v0_1/search.json"
refreshTokenExpirySeconds = 31532400
chatPollIntervalSeconds = 0.5
chatUrls = {
    termsAndConditions = "https://www.gov.uk/guidance/govuk-chat-terms-and-conditions"
    privacyNotice = "https://www.gov.uk/government/publications/govuk-chat-privacy-notice"
    about = "https://www.gov.uk/guidance/about-govuk-chat"
    feedback = "https://surveys.publishing.service.gov.uk/s/SUIEH2/"
}
userFeedbackBanner = {
  body = "Tell us what you think about the app"
  link = {
   title = "Give feedback"
   url = "https://www.gov.uk/contact/govuk-app"
  }
}
alertBanner = {
  id = "govuk_improve_app_alert_10_2025"
  body = "Help improve the app"
  link = {
   title = "Take a 5 minute survey"
   url = "https://surveys.publishing.service.gov.uk/s/GOVUK-APP"
  }
}