[metadata]
configVersion = "0.0.2"

[environments]
production = { }
staging = { }
integration = { }

[environments.default.android]
platform = "Android"
available = true
minimumVersion = "0.0.1"
recommendedVersion = "0.0.1"
releaseFlags = {
    onboarding = true
    search = true
    topics = true
}

[environments.default.ios]
platform = "iOS"
available = true
minimumVersion = "0.0.1"
recommendedVersion = "0.0.1"
releaseFlags = {
    onboarding = true
    search = true
    topics = true
}
