name: Deploy config to Production
on:
  workflow_dispatch:

env:
  BUCKET_NAME: govuk-app-remote-config-production

jobs:
  deploy-production:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
    - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # pin to 6.0.3
    - name: Setup Node.js
      uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # pin to 6.4.0
    - name: Install dependencies
      run: npm ci
    - name: Configure AWS credentials for KMS (Production)
      uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502 # 4.0.2
      with:
        role-to-assume: "arn:aws:iam::172025368201:role/github_action_mobile_backend_sign_deploy"
        role-session-name: gha-sign-mobile-backend-config
        aws-region: eu-west-1
    - name: Build config for production
      run: npm start build -- production --output-directory ./config
    - name: Minify files
      run: find config static -type f | xargs tools/minify-json.sh
    - name: Generate signatures
      run: find config static -type f | xargs tools/create-signature.sh
    - name: Deploy to S3
      run: find config static -type f | xargs tools/deploy-signed-json.sh
    - name: Clean up deleted files - config
      run: aws s3 sync --delete config "s3://$BUCKET_NAME/config"
    - name: Clean up deleted files - static
      run: aws s3 sync --delete static "s3://$BUCKET_NAME/static"

  fastly-purge-production:
    needs: deploy-production
    uses: ./.github/workflows/fastly-purge-production.yaml
    secrets: inherit
