name: Deploy config
on:
  push:
    branches:
      - main
jobs:
  deploy-integration:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
    - uses: actions/checkout@v4
    - name: Setup Node.js
      uses: actions/setup-node@v4
    - name: Install dependencies
      run: npm ci
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: "arn:aws:iam::172025368201:role/github_action_config_signing"
        role-session-name: gha-sign-mobile-backend-config
        aws-region: eu-west-1
    - name: Build config for integration
      run: npm start build -- integration --key-id alias/config-signing-key
    - name: Deploy appinfo to S3
      run: cat ./config.out/appinfo/* # just a placeholder for a real S3 command
