name: Run application tests

on:
  push:
    paths:
      - src/**
      - test/**

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # pin to 4.2.2
    - name: Setup Node.js
      uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # pin to 4.1.0
    - name: Install dependencies
      run: npm ci
    - name: Run tests and lint
      run: npm test
