name: Validate config version documents
on: [push]
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # pin to 4.2.2
    - name: Setup Node.js
      uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # pin to 4.1.0
    - name: Install dependencies
      run: npm ci
    - name: Validate documents
      run: find versions -name *.toml | xargs npm start validate
    - name: Validate static JSON
      run: find static -type f | xargs tools/json-check.sh
    - name: Check for duplicate topic data
      run: node tools/dupe-detect.js
